# Generated by Django 5.0.6 on 2024-05-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('nascimento', models.DateField()),
                ('cpf', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.TextField(max_length=255)),
                ('doenca', models.TextField(max_length=255)),
                ('password', models.TextField(max_length=255)),
            ],
        ),
    ]
